[package]
name = "mdx_plugin_toc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
markdown = { workspace = true }
slugger = { path = "../slugger" }